# TCL File Generated by Component Editor 13.1
# Wed Mar 19 23:05:07 PDT 2014
# DO NOT MODIFY


# 
# multiply_by_constant_avalon_st "Avalon ST Multiply By Constant" v1.0
#  2014.03.19.23:05:07
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module multiply_by_constant_avalon_st
# 
set_module_property DESCRIPTION ""
set_module_property NAME multiply_by_constant_avalon_st
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon ST Multiply By Constant"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL multiply_by_constant_avalon_st
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file multiply_by_constant_avalon_st.sv VERILOG PATH multiply_by_constant_avalon_st.sv TOP_LEVEL_FILE
add_fileset_file constant_multiplier.sv VERILOG PATH constant_multiplier.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL multiply_by_constant_avalon_st
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file multiply_by_constant_avalon_st.sv VERILOG_INCLUDE PATH multiply_by_constant_avalon_st.sv
add_fileset_file constant_multiplier.sv VERILOG PATH constant_multiplier.sv


# 
# parameters
# 
add_parameter IN_WIDTH INTEGER 8 ""
set_parameter_property IN_WIDTH DEFAULT_VALUE 8
set_parameter_property IN_WIDTH DISPLAY_NAME IN_WIDTH
set_parameter_property IN_WIDTH TYPE INTEGER
set_parameter_property IN_WIDTH UNITS None
set_parameter_property IN_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IN_WIDTH DESCRIPTION ""
set_parameter_property IN_WIDTH HDL_PARAMETER true
add_parameter OUT_WIDTH INTEGER 11
set_parameter_property OUT_WIDTH DEFAULT_VALUE 11
set_parameter_property OUT_WIDTH DISPLAY_NAME OUT_WIDTH
set_parameter_property OUT_WIDTH TYPE INTEGER
set_parameter_property OUT_WIDTH UNITS None
set_parameter_property OUT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OUT_WIDTH HDL_PARAMETER true
add_parameter MULTIPLIER INTEGER 2 ""
set_parameter_property MULTIPLIER DEFAULT_VALUE 2
set_parameter_property MULTIPLIER DISPLAY_NAME MULTIPLIER
set_parameter_property MULTIPLIER TYPE INTEGER
set_parameter_property MULTIPLIER UNITS None
set_parameter_property MULTIPLIER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MULTIPLIER DESCRIPTION ""
set_parameter_property MULTIPLIER HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock clock
set_interface_property in associatedReset reset
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 0
set_interface_property in readyLatency 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in in_ready ready Output 1
add_interface_port in in_valid valid Input 1
add_interface_port in in_data data Input IN_WIDTH
add_interface_port in in_startofpacket startofpacket Input 1
add_interface_port in in_endofpacket endofpacket Input 1


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clock
set_interface_property out associatedReset reset
set_interface_property out dataBitsPerSymbol 1
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out out_ready ready Input 1
add_interface_port out out_valid valid Output 1
add_interface_port out out_data data Output OUT_WIDTH
add_interface_port out out_startofpacket startofpacket Output 1
add_interface_port out out_endofpacket endofpacket Output 1

