# TCL File Generated by Component Editor 13.1
# Thu Mar 27 23:35:09 PDT 2014
# DO NOT MODIFY


# 
# st_to_mem "Avalon ST to Memory Adapter" v1.0
#  2014.03.27.23:35:09
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module st_to_mem
# 
set_module_property DESCRIPTION ""
set_module_property NAME st_to_mem
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon ST to Memory Adapter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL st_to_mem
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file st_to_mem.sv SYSTEM_VERILOG PATH st_to_mem.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL st_to_mem
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file st_to_mem.sv SYSTEM_VERILOG PATH st_to_mem.sv


# 
# parameters
# 
add_parameter IN_WIDTH INTEGER 32
set_parameter_property IN_WIDTH DEFAULT_VALUE 32
set_parameter_property IN_WIDTH DISPLAY_NAME IN_WIDTH
set_parameter_property IN_WIDTH TYPE INTEGER
set_parameter_property IN_WIDTH UNITS None
set_parameter_property IN_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IN_WIDTH HDL_PARAMETER true
add_parameter WRITE_WIDTH INTEGER 256 ""
set_parameter_property WRITE_WIDTH DEFAULT_VALUE 256
set_parameter_property WRITE_WIDTH DISPLAY_NAME WRITE_WIDTH
set_parameter_property WRITE_WIDTH TYPE INTEGER
set_parameter_property WRITE_WIDTH UNITS None
set_parameter_property WRITE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WRITE_WIDTH DESCRIPTION ""
set_parameter_property WRITE_WIDTH HDL_PARAMETER true
add_parameter ADDRESS_WIDTH INTEGER 32 ""
set_parameter_property ADDRESS_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME ADDRESS_WIDTH
set_parameter_property ADDRESS_WIDTH TYPE INTEGER
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS_WIDTH DESCRIPTION ""
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true
add_parameter COUNT_WIDTH INTEGER 3
set_parameter_property COUNT_WIDTH DEFAULT_VALUE 3
set_parameter_property COUNT_WIDTH DISPLAY_NAME COUNT_WIDTH
set_parameter_property COUNT_WIDTH TYPE INTEGER
set_parameter_property COUNT_WIDTH UNITS None
set_parameter_property COUNT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COUNT_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink in_ready ready Output 1
add_interface_port avalon_streaming_sink in_valid valid Input 1
add_interface_port avalon_streaming_sink in_data data Input IN_WIDTH
add_interface_port avalon_streaming_sink in_sop startofpacket Input 1
add_interface_port avalon_streaming_sink in_eop endofpacket Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_write write Input 1
add_interface_port csr csr_writedata writedata Input ADDRESS_WIDTH
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point mm_out
# 
add_interface mm_out avalon start
set_interface_property mm_out addressUnits SYMBOLS
set_interface_property mm_out associatedClock clock
set_interface_property mm_out associatedReset reset
set_interface_property mm_out bitsPerSymbol 8
set_interface_property mm_out burstOnBurstBoundariesOnly false
set_interface_property mm_out burstcountUnits WORDS
set_interface_property mm_out doStreamReads false
set_interface_property mm_out doStreamWrites false
set_interface_property mm_out holdTime 0
set_interface_property mm_out linewrapBursts false
set_interface_property mm_out maximumPendingReadTransactions 0
set_interface_property mm_out readLatency 0
set_interface_property mm_out readWaitTime 1
set_interface_property mm_out setupTime 0
set_interface_property mm_out timingUnits Cycles
set_interface_property mm_out writeWaitTime 0
set_interface_property mm_out ENABLED true
set_interface_property mm_out EXPORT_OF ""
set_interface_property mm_out PORT_NAME_MAP ""
set_interface_property mm_out CMSIS_SVD_VARIABLES ""
set_interface_property mm_out SVD_ADDRESS_GROUP ""

add_interface_port mm_out out_write write Output 1
add_interface_port mm_out out_address address Output ADDRESS_WIDTH
add_interface_port mm_out out_waitrequest waitrequest Input 1
add_interface_port mm_out out_writedata writedata Output WRITE_WIDTH

