# TCL File Generated by Component Editor 13.1
# Wed Mar 26 14:42:04 PDT 2014
# DO NOT MODIFY


# 
# ordered_merge_avalon_st "Avalon ST Ordered Merge" v1.0
#  2014.03.26.14:42:04
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module ordered_merge_avalon_st
# 
set_module_property DESCRIPTION ""
set_module_property NAME ordered_merge_avalon_st
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon ST Ordered Merge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ordered_merge_avalon_st
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ordered_merge_avalon_st.sv SYSTEM_VERILOG PATH ordered_merge_avalon_st.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ordered_merge_avalon_st
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ordered_merge_avalon_st.sv SYSTEM_VERILOG PATH ordered_merge_avalon_st.sv


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 8
set_parameter_property DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter CSR_WIDTH INTEGER 8
set_parameter_property CSR_WIDTH DEFAULT_VALUE 8
set_parameter_property CSR_WIDTH DISPLAY_NAME CSR_WIDTH
set_parameter_property CSR_WIDTH TYPE INTEGER
set_parameter_property CSR_WIDTH UNITS None
set_parameter_property CSR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_WIDTH HDL_PARAMETER true
add_parameter SEND_ENDOFPACKET STD_LOGIC_VECTOR 1
set_parameter_property SEND_ENDOFPACKET DEFAULT_VALUE 1
set_parameter_property SEND_ENDOFPACKET DISPLAY_NAME SEND_ENDOFPACKET
set_parameter_property SEND_ENDOFPACKET TYPE STD_LOGIC_VECTOR
set_parameter_property SEND_ENDOFPACKET UNITS None
set_parameter_property SEND_ENDOFPACKET ALLOWED_RANGES 0:3
set_parameter_property SEND_ENDOFPACKET HDL_PARAMETER true
add_parameter END_PACKET_VALUE STD_LOGIC_VECTOR -1 ""
set_parameter_property END_PACKET_VALUE DEFAULT_VALUE -1
set_parameter_property END_PACKET_VALUE DISPLAY_NAME END_PACKET_VALUE
set_parameter_property END_PACKET_VALUE WIDTH 32
set_parameter_property END_PACKET_VALUE TYPE STD_LOGIC_VECTOR
set_parameter_property END_PACKET_VALUE UNITS None
set_parameter_property END_PACKET_VALUE DESCRIPTION ""
set_parameter_property END_PACKET_VALUE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point a_in
# 
add_interface a_in avalon_streaming end
set_interface_property a_in associatedClock clock
set_interface_property a_in associatedReset reset
set_interface_property a_in dataBitsPerSymbol 1
set_interface_property a_in errorDescriptor ""
set_interface_property a_in firstSymbolInHighOrderBits true
set_interface_property a_in maxChannel 0
set_interface_property a_in readyLatency 0
set_interface_property a_in ENABLED true
set_interface_property a_in EXPORT_OF ""
set_interface_property a_in PORT_NAME_MAP ""
set_interface_property a_in CMSIS_SVD_VARIABLES ""
set_interface_property a_in SVD_ADDRESS_GROUP ""

add_interface_port a_in a_valid valid Input 1
add_interface_port a_in a_data data Input DATA_WIDTH
add_interface_port a_in a_ready ready Output 1
add_interface_port a_in a_startofpacket startofpacket Input 1
add_interface_port a_in a_endofpacket endofpacket Input 1


# 
# connection point b_in
# 
add_interface b_in avalon_streaming end
set_interface_property b_in associatedClock clock
set_interface_property b_in associatedReset reset
set_interface_property b_in dataBitsPerSymbol 1
set_interface_property b_in errorDescriptor ""
set_interface_property b_in firstSymbolInHighOrderBits true
set_interface_property b_in maxChannel 0
set_interface_property b_in readyLatency 0
set_interface_property b_in ENABLED true
set_interface_property b_in EXPORT_OF ""
set_interface_property b_in PORT_NAME_MAP ""
set_interface_property b_in CMSIS_SVD_VARIABLES ""
set_interface_property b_in SVD_ADDRESS_GROUP ""

add_interface_port b_in b_ready ready Output 1
add_interface_port b_in b_valid valid Input 1
add_interface_port b_in b_data data Input DATA_WIDTH
add_interface_port b_in b_startofpacket startofpacket Input 1
add_interface_port b_in b_endofpacket endofpacket Input 1


# 
# connection point merge_out
# 
add_interface merge_out avalon_streaming start
set_interface_property merge_out associatedClock clock
set_interface_property merge_out associatedReset reset
set_interface_property merge_out dataBitsPerSymbol 1
set_interface_property merge_out errorDescriptor ""
set_interface_property merge_out firstSymbolInHighOrderBits true
set_interface_property merge_out maxChannel 0
set_interface_property merge_out readyLatency 0
set_interface_property merge_out ENABLED true
set_interface_property merge_out EXPORT_OF ""
set_interface_property merge_out PORT_NAME_MAP ""
set_interface_property merge_out CMSIS_SVD_VARIABLES ""
set_interface_property merge_out SVD_ADDRESS_GROUP ""

add_interface_port merge_out out_ready ready Input 1
add_interface_port merge_out out_valid valid Output 1
add_interface_port merge_out out_data data Output DATA_WIDTH
add_interface_port merge_out out_startofpacket startofpacket Output 1
add_interface_port merge_out out_endofpacket endofpacket Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_write write Input 1
add_interface_port csr csr_readdata readdata Output CSR_WIDTH
add_interface_port csr csr_writedata writedata Input CSR_WIDTH
add_interface_port csr csr_address address Input 3
add_interface_port csr csr_read read Input 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0

