# TCL File Generated by Component Editor 13.1
# Wed Mar 19 23:19:15 PDT 2014
# DO NOT MODIFY


# 
# priority_merge_avalon_st "Avalon ST Priority Merge" v1.0
#  2014.03.19.23:19:15
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module priority_merge_avalon_st
# 
set_module_property DESCRIPTION ""
set_module_property NAME priority_merge_avalon_st
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon ST Priority Merge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL priority_merge_avalon_st
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file priority_merge_avalon_st.sv SYSTEM_VERILOG PATH priority_merge_avalon_st.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL priority_merge_avalon_st
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file priority_merge_avalon_st.sv SYSTEM_VERILOG PATH priority_merge_avalon_st.sv


# 
# parameters
# 
add_parameter WIDTH INTEGER 8
set_parameter_property WIDTH DEFAULT_VALUE 8
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point in_a
# 
add_interface in_a avalon_streaming end
set_interface_property in_a associatedClock clock
set_interface_property in_a associatedReset reset
set_interface_property in_a dataBitsPerSymbol 8
set_interface_property in_a errorDescriptor ""
set_interface_property in_a firstSymbolInHighOrderBits true
set_interface_property in_a maxChannel 0
set_interface_property in_a readyLatency 0
set_interface_property in_a ENABLED true
set_interface_property in_a EXPORT_OF ""
set_interface_property in_a PORT_NAME_MAP ""
set_interface_property in_a CMSIS_SVD_VARIABLES ""
set_interface_property in_a SVD_ADDRESS_GROUP ""

add_interface_port in_a a_valid valid Input 1
add_interface_port in_a a_data data Input WIDTH
add_interface_port in_a a_ready ready Output 1
add_interface_port in_a a_startofpacket startofpacket Input 1
add_interface_port in_a a_endofpacket endofpacket Input 1


# 
# connection point in_b
# 
add_interface in_b avalon_streaming end
set_interface_property in_b associatedClock clock
set_interface_property in_b associatedReset reset
set_interface_property in_b dataBitsPerSymbol 8
set_interface_property in_b errorDescriptor ""
set_interface_property in_b firstSymbolInHighOrderBits true
set_interface_property in_b maxChannel 0
set_interface_property in_b readyLatency 0
set_interface_property in_b ENABLED true
set_interface_property in_b EXPORT_OF ""
set_interface_property in_b PORT_NAME_MAP ""
set_interface_property in_b CMSIS_SVD_VARIABLES ""
set_interface_property in_b SVD_ADDRESS_GROUP ""

add_interface_port in_b b_ready ready Output 1
add_interface_port in_b b_valid valid Input 1
add_interface_port in_b b_data data Input WIDTH
add_interface_port in_b b_startofpacket startofpacket Input 1
add_interface_port in_b b_endofpacket endofpacket Input 1


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clock
set_interface_property out associatedReset reset
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out out_valid valid Output 1
add_interface_port out out_data data Output WIDTH
add_interface_port out out_ready ready Input 1
add_interface_port out out_startofpacket startofpacket Output 1
add_interface_port out out_endofpacket endofpacket Output 1

