# TCL File Generated by Component Editor 13.1
# Wed Feb 19 20:19:20 PST 2014
# DO NOT MODIFY


# 
# st_delimiter_remover "Avalon ST delimiter remover" v1.0
#  2014.02.19.20:19:20
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module st_delimiter_remover
# 
set_module_property DESCRIPTION ""
set_module_property NAME st_delimiter_remover
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon ST delimiter remover"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL st_delimiter_remover
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file st_delimiter_remover.sv SYSTEM_VERILOG PATH st_delimiter_remover.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL st_delimiter_remover
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file st_delimiter_remover.sv SYSTEM_VERILOG PATH st_delimiter_remover.sv


# 
# parameters
# 
add_parameter WIDTH INTEGER 8
set_parameter_property WIDTH DEFAULT_VALUE 8
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter DELIMITER_VALUE_PASSTHRU INTEGER 0
set_parameter_property DELIMITER_VALUE_PASSTHRU DEFAULT_VALUE 0
set_parameter_property DELIMITER_VALUE_PASSTHRU DISPLAY_NAME DELIMITER_VALUE_PASSTHRU
set_parameter_property DELIMITER_VALUE_PASSTHRU TYPE INTEGER
set_parameter_property DELIMITER_VALUE_PASSTHRU UNITS None
set_parameter_property DELIMITER_VALUE_PASSTHRU ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DELIMITER_VALUE_PASSTHRU HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point st_data_output
# 
add_interface st_data_output avalon_streaming start
set_interface_property st_data_output associatedClock clock
set_interface_property st_data_output associatedReset reset
set_interface_property st_data_output dataBitsPerSymbol 8
set_interface_property st_data_output errorDescriptor ""
set_interface_property st_data_output firstSymbolInHighOrderBits true
set_interface_property st_data_output maxChannel 0
set_interface_property st_data_output readyLatency 0
set_interface_property st_data_output ENABLED true
set_interface_property st_data_output EXPORT_OF ""
set_interface_property st_data_output PORT_NAME_MAP ""
set_interface_property st_data_output CMSIS_SVD_VARIABLES ""
set_interface_property st_data_output SVD_ADDRESS_GROUP ""

add_interface_port st_data_output out_ready ready Input 1
add_interface_port st_data_output out_valid valid Output 1
add_interface_port st_data_output out_data data Output WIDTH


# 
# connection point st_data_input
# 
add_interface st_data_input avalon_streaming end
set_interface_property st_data_input associatedClock clock
set_interface_property st_data_input associatedReset reset
set_interface_property st_data_input dataBitsPerSymbol 8
set_interface_property st_data_input errorDescriptor ""
set_interface_property st_data_input firstSymbolInHighOrderBits true
set_interface_property st_data_input maxChannel 0
set_interface_property st_data_input readyLatency 0
set_interface_property st_data_input ENABLED true
set_interface_property st_data_input EXPORT_OF ""
set_interface_property st_data_input PORT_NAME_MAP ""
set_interface_property st_data_input CMSIS_SVD_VARIABLES ""
set_interface_property st_data_input SVD_ADDRESS_GROUP ""

add_interface_port st_data_input in_ready ready Output 1
add_interface_port st_data_input in_data data Input WIDTH
add_interface_port st_data_input in_valid valid Input 1
add_interface_port st_data_input in_sop startofpacket Input 1
add_interface_port st_data_input in_eop endofpacket Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_readdata readdata Output 8
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0

