# TCL File Generated by Component Editor 13.1
# Fri Jan 10 18:34:58 PST 2014
# DO NOT MODIFY


# 
# mypwmled "mypwmled" v1.0
#  2014.01.10.18:34:58
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module mypwmled
# 
set_module_property DESCRIPTION ""
set_module_property NAME mypwmled
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mypwmled
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mypwmled
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mypwmled.v VERILOG PATH mypwmled.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL mypwmled
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mypwmled.v VERILOG PATH mypwmled.v


# 
# parameters
# 
add_parameter scratchreg_on_reset STD_LOGIC_VECTOR 0
set_parameter_property scratchreg_on_reset DEFAULT_VALUE 0
set_parameter_property scratchreg_on_reset DISPLAY_NAME scratchreg_on_reset
set_parameter_property scratchreg_on_reset TYPE STD_LOGIC_VECTOR
set_parameter_property scratchreg_on_reset UNITS None
set_parameter_property scratchreg_on_reset ALLOWED_RANGES 0:17179869183
set_parameter_property scratchreg_on_reset HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_mm_slave
# 
add_interface avalon_mm_slave avalon end
set_interface_property avalon_mm_slave addressUnits WORDS
set_interface_property avalon_mm_slave associatedClock clock_input
set_interface_property avalon_mm_slave associatedReset reset_input
set_interface_property avalon_mm_slave bitsPerSymbol 8
set_interface_property avalon_mm_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_mm_slave burstcountUnits WORDS
set_interface_property avalon_mm_slave explicitAddressSpan 0
set_interface_property avalon_mm_slave holdTime 0
set_interface_property avalon_mm_slave linewrapBursts false
set_interface_property avalon_mm_slave maximumPendingReadTransactions 0
set_interface_property avalon_mm_slave readLatency 0
set_interface_property avalon_mm_slave readWaitTime 1
set_interface_property avalon_mm_slave setupTime 0
set_interface_property avalon_mm_slave timingUnits Cycles
set_interface_property avalon_mm_slave writeWaitTime 0
set_interface_property avalon_mm_slave ENABLED true
set_interface_property avalon_mm_slave EXPORT_OF ""
set_interface_property avalon_mm_slave PORT_NAME_MAP ""
set_interface_property avalon_mm_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_mm_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_mm_slave address address Input 1
add_interface_port avalon_mm_slave readdata readdata Output 32
add_interface_port avalon_mm_slave read read Input 1
add_interface_port avalon_mm_slave write write Input 1
add_interface_port avalon_mm_slave writedata writedata Input 32
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_input
# 
add_interface reset_input reset end
set_interface_property reset_input associatedClock clock_input
set_interface_property reset_input synchronousEdges DEASSERT
set_interface_property reset_input ENABLED true
set_interface_property reset_input EXPORT_OF ""
set_interface_property reset_input PORT_NAME_MAP ""
set_interface_property reset_input CMSIS_SVD_VARIABLES ""
set_interface_property reset_input SVD_ADDRESS_GROUP ""

add_interface_port reset_input reset reset Input 1


# 
# connection point clock_input
# 
add_interface clock_input clock end
set_interface_property clock_input clockRate 0
set_interface_property clock_input ENABLED true
set_interface_property clock_input EXPORT_OF ""
set_interface_property clock_input PORT_NAME_MAP ""
set_interface_property clock_input CMSIS_SVD_VARIABLES ""
set_interface_property clock_input SVD_ADDRESS_GROUP ""

add_interface_port clock_input clock clk Input 1


# 
# connection point led_output_conduit
# 
add_interface led_output_conduit conduit end
set_interface_property led_output_conduit associatedClock clock_input
set_interface_property led_output_conduit associatedReset reset_input
set_interface_property led_output_conduit ENABLED true
set_interface_property led_output_conduit EXPORT_OF ""
set_interface_property led_output_conduit PORT_NAME_MAP ""
set_interface_property led_output_conduit CMSIS_SVD_VARIABLES ""
set_interface_property led_output_conduit SVD_ADDRESS_GROUP ""

add_interface_port led_output_conduit pwmled export Output 1

